# Generated by Django 4.0.6 on 2022-07-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220728_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_principale', models.ImageField(upload_to='images')),
                ('photos_secondaires', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='creations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
