# Generated by Django 4.0.6 on 2022-10-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220827_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
