# Generated by Django 3.1.6 on 2022-07-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220728_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creations',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
